# Generated by Django 4.2.15 on 2024-08-08 21:54

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('text', models.TextField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutme', ckeditor.fields.RichTextField()),
                ('name1', models.CharField(max_length=255)),
                ('number1', models.PositiveIntegerField(default=0)),
                ('name2', models.CharField(max_length=255)),
                ('number2', models.PositiveIntegerField(default=0)),
                ('name3', models.CharField(max_length=255)),
                ('number3', models.PositiveIntegerField(default=0)),
                ('what_can_i_do_title1', models.CharField(max_length=355)),
                ('wcid_des1', models.TextField()),
                ('what_can_i_do_title2', models.CharField(max_length=355)),
                ('wcid_des2', models.TextField()),
                ('what_can_i_do_title3', models.CharField(max_length=355)),
                ('wcid_des3', models.TextField()),
                ('aboutme_title', models.CharField(max_length=355)),
                ('aboutme_des', models.TextField()),
                ('aboutme_image', models.ImageField(upload_to='cover')),
                ('email', models.EmailField(max_length=200)),
                ('address', models.CharField(max_length=555)),
                ('phone', models.CharField(max_length=150)),
                ('img1', models.ImageField(upload_to='cover')),
                ('img2', models.ImageField(upload_to='cover')),
                ('img3', models.ImageField(upload_to='cover')),
                ('img4', models.ImageField(upload_to='cover')),
                ('img5', models.ImageField(upload_to='cover')),
                ('img6', models.ImageField(upload_to='cover')),
                ('blog_img1', models.ImageField(upload_to='cover')),
                ('blog_title1', models.CharField(max_length=455)),
                ('des_title1', ckeditor.fields.RichTextField()),
                ('blog_img2', models.ImageField(upload_to='cover')),
                ('blog_title2', models.CharField(max_length=455)),
                ('des_title2', ckeditor.fields.RichTextField()),
                ('blog_img3', models.ImageField(upload_to='cover')),
                ('blog_title3', models.CharField(max_length=455)),
                ('des_title3', ckeditor.fields.RichTextField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill', models.CharField(max_length=100)),
                ('percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('vars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='main.vars')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='company')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='main.vars')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Customers')),
                ('name', models.CharField(max_length=150)),
                ('des', models.CharField(max_length=150)),
                ('Customer_opinion', models.TextField(max_length=350)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='main.vars')),
            ],
        ),
    ]
