# Generated by Django 4.2.15 on 2024-08-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_images_comimages_customer_customer_opinion_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vars',
            name='kherad',
            field=models.URLField(blank=True),
        ),
    ]
