# Generated by Django 4.2.15 on 2024-08-09 14:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_vars_kherad'),
    ]

    operations = [
        migrations.AddField(
            model_name='vars',
            name='sub_des1',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='vars',
            name='sub_des2',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='vars',
            name='sub_des3',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='vars',
            name='wcid_img1',
            field=models.ImageField(blank=True, upload_to='cover'),
        ),
        migrations.AddField(
            model_name='vars',
            name='wcid_img2',
            field=models.ImageField(blank=True, upload_to='cover'),
        ),
        migrations.AddField(
            model_name='vars',
            name='wcid_img3',
            field=models.ImageField(blank=True, upload_to='cover'),
        ),
        migrations.AlterField(
            model_name='vars',
            name='wcid_des1',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vars',
            name='wcid_des1_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vars',
            name='wcid_des1_fa',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vars',
            name='wcid_des2',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vars',
            name='wcid_des2_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vars',
            name='wcid_des2_fa',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vars',
            name='wcid_des3',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vars',
            name='wcid_des3_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vars',
            name='wcid_des3_fa',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
