# Generated by Django 4.2.15 on 2024-08-09 14:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_vars_sub_des1_vars_sub_des2_vars_sub_des3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vars',
            name='sub_des1_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vars',
            name='sub_des1_fa',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vars',
            name='sub_des2_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vars',
            name='sub_des2_fa',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vars',
            name='sub_des3_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vars',
            name='sub_des3_fa',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
