# Generated by Django 4.2.15 on 2024-08-09 14:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_vars_sub_des1_en_vars_sub_des1_fa_vars_sub_des2_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vars',
            name='aboutme_des',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vars',
            name='aboutme_des_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vars',
            name='aboutme_des_fa',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
