# Generated by Django 4.2.15 on 2024-08-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_vars_aboutme_des_alter_vars_aboutme_des_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vars',
            name='file',
            field=models.FileField(blank=True, upload_to='pdfs/'),
        ),
    ]
