# Generated by Django 4.2.15 on 2024-08-09 15:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_vars_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vars',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='vars',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='vars',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='vars',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='vars',
            name='img5',
        ),
        migrations.RemoveField(
            model_name='vars',
            name='img6',
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='cover')),
                ('title', models.CharField(max_length=400)),
                ('des', ckeditor.fields.RichTextField()),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Job', to='main.vars')),
            ],
        ),
    ]
