# Generated by Django 4.2.15 on 2024-08-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_job_des_en_job_des_fa_job_title_en_job_title_fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='comimages',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
