# Generated by Django 4.2.15 on 2024-08-09 16:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_comimages_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_img', models.ImageField(upload_to='cover')),
                ('blog_title', models.CharField(max_length=455)),
                ('des', models.TextField()),
                ('sub_des', ckeditor.fields.RichTextField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vars',
            name='blog_img1',
        ),
        migrations.RemoveField(
            model_name='vars',
            name='blog_img2',
        ),
        migrations.RemoveField(
            model_name='vars',
            name='blog_img3',
        ),
        migrations.RemoveField(
            model_name='vars',
            name='blog_title1',
        ),
        migrations.RemoveField(
            model_name='vars',
            name='blog_title1_en',
        ),
        migrations.RemoveField(
            model_name='vars',
            name='blog_title1_fa',
        ),
        migrations.RemoveField(
            model_name='vars',
            name='blog_title2',
        ),
        migrations.RemoveField(
            model_name='vars',
            name='blog_title2_en',
        ),
        migrations.RemoveField(
            model_name='vars',
            name='blog_title2_fa',
        ),
        migrations.RemoveField(
            model_name='vars',
            name='blog_title3',
        ),
        migrations.RemoveField(
            model_name='vars',
            name='blog_title3_en',
        ),
        migrations.RemoveField(
            model_name='vars',
            name='blog_title3_fa',
        ),
        migrations.RemoveField(
            model_name='vars',
            name='des_title1',
        ),
        migrations.RemoveField(
            model_name='vars',
            name='des_title1_en',
        ),
        migrations.RemoveField(
            model_name='vars',
            name='des_title1_fa',
        ),
        migrations.RemoveField(
            model_name='vars',
            name='des_title2',
        ),
        migrations.RemoveField(
            model_name='vars',
            name='des_title2_en',
        ),
        migrations.RemoveField(
            model_name='vars',
            name='des_title2_fa',
        ),
        migrations.RemoveField(
            model_name='vars',
            name='des_title3',
        ),
        migrations.RemoveField(
            model_name='vars',
            name='des_title3_en',
        ),
        migrations.RemoveField(
            model_name='vars',
            name='des_title3_fa',
        ),
    ]
