# Generated by Django 4.2.15 on 2024-08-09 16:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_blog_remove_vars_blog_img1_remove_vars_blog_img2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_title_en',
            field=models.CharField(max_length=455, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_title_fa',
            field=models.CharField(max_length=455, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='des_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='des_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='sub_des_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='sub_des_fa',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
