# Generated by Django 4.2.15 on 2024-08-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_blog_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='vars',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vars',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vars',
            name='telegram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vars',
            name='whatsapp',
            field=models.URLField(blank=True),
        ),
    ]
