# Generated by Django 4.2.15 on 2024-08-10 18:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_vars_instagram_vars_linkedin_vars_telegram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Customer_opinion',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Customer_opinion_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Customer_opinion_fa',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
